### ISSUE TITLE
Additional Database Functionality

### ISSUE THREAD

**Issue by Senney** [Senney/MediTalk#7]
1) doesUserExist(username, callback) - boolean into callback - Checks if the user exists in the table.
2) doesSectionExist(section, callback) - boolean into callback - Checks if the section exists already in the table.
3) removeUserByName(username) - none - Removes a user by username
4) getRecentPosts(section, numPosts, callback) - recent posts into callback - Gets the recent posts from the section specified by -name-. NOTE: If section == 'all', it grabs the top 10 posts from the posts database, instead of based on section.

**Comment by BrenTicus** [comment]
Added all functionality. Removing users by name is names delUserN to be consistent with other functions.
